apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - image: jacobalberty/unifi:latest
        name: unifi-controller
        ports:
        - containerPort: 8443
        - containerPort: 8080
        - containerPort: 8843
        - containerPort: 8880
        - containerPort: 3478/udp
        volumeMounts:
        - mountPath: /unifi
          name: unifi-data
      volumes:
      - name: unifi-data
        persistentVolumeClaim:
          claimName: unifi-data-pvc
