---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: unifi-controller
  namespace: unifi-controller
spec:
  rules:
  - host: unifi123.rajhmlab.duckdns.org
    http:
      paths:
      - backend:
          service:
            name: unifi-controller
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - unifi123.rajhmlab.duckdns.org
